-- Your SQL goes here
CREATE TABLE users(id INTEGER PRIMARY KEY NOT NULL, username VARCHAR(20) NOT NULL);
CREATE TABLE cards(id INTEGER PRIMARY KEY NOT NULL, tags TEXT(500) NOT NULL, front TEXT(1000) NOT NULL, back TEXT(1000) NOT NULL, impls INTEGER NOT NULL);
CREATE TABLE decks(id INTEGER PRIMARY KEY NOT NULL, title VARCHAR(50) NOT NULL, description TEXT(500) NOT NULL, tags TEXT(500) NOT NULL, cards TEXT(1000) NOT NULL);