-- Your SQL goes here
CREATE TABLE users(id INTEGER PRIMARY KEY NOT NULL, username VARCHAR NOT NULL);
CREATE TABLE cards(id INTEGER PRIMARY KEY NOT NULL, tags TEXT NOT NULL, front TEXT NOT NULL, back TEXT NOT NULL, impls INTEGER NOT NULL);
CREATE TABLE decks(id INTEGER PRIMARY KEY NOT NULL, title VARCHAR NOT NULL, description TEXT NOT NULL, tags TEXT NOT NULL, cards TEXT NOT NULL);